apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "https://trace-api.newrelic.com/trace/v1?Api-Key=NRAK-HR6884KJMUQ9HLN1ZLDZFEVTYUB&Data-Format=zipkin&Data-Format-Version=2"